version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.3
    - 2.13.4
    - 2.14.0
    - 2.14.1
    - 2.14.3
  - dependency-name: write-good
    versions:
    - 1.0.4
    - 1.0.5
    - 1.0.6
    - 1.0.7
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.12.0
    - 2.13.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
    - 3.11.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
